export const ACTION_TYPES = {
  //Users
  SET_ADMIN: "SET_ADMIN",
  GET_DEACTIVATE_USERS: "GET_DEACTIVATE_USERS",
  UPDATE_USER_STATUS: "UPDATE_USER_STATUS",

  //Categories
  SET_CATEGORY: "SET_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  GET_CATEGORIES: "GET_CATEGORIES",
  DELETE_CATEGORIES: "DELETE_CATEGORIES",

  //Sub-Categories
  SET_SUB_CATEGORY: "SET_SUB_CATEGORY",
  UPDATE_SUB_CATEGORY: "UPDATE_SUB_CATEGORY",
  GET_SUB_CATEGORIES: "GET_SUB_CATEGORIES",
  DELETE_SUB_CATEGORY: "DELETE_SUB_CATEGORY",

  //Softwares
  SET_SOFTWARE: "SET_SOFTWARE",
  UPDATE_SOFTWARE: "UPDATE_SOFTWARE",
  GET_SOFTWARES: "GET_SOFTWARES",
  DELETE_SOFTWARES: "DELETE_SOFTWARES",

  //Customers Messages
  GET_CUSTOMERS_MESSAGES: "GET_CUSTOMERS_MESSAGES",
  DELETE_CUSTOMERS_MESSAGES: "DELETE_CUSTOMERS_MESSAGES",
  SUBMIT_RESPONSE_ON_CUSTOMERS_MESSAGES:
    "SUBMIT_RESPONSE_ON_CUSTOMERS_MESSAGES",

  //progress
  PROGRESS_BAR_STATE: "PROGRESS_BAR_STATE",

  //login
  LOGIN: "LOGIN",
};
